AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function


Resources:
  Test:
    Type: AWS::Serverless::Function
    Properties:
      Handler:  dist/index.handler
      Runtime: nodejs14.x
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
  