#! /usr/bin/env bash

LAMBDA_NAME=$(cat $(pwd)/scripts/lambda-name | xargs)

aws lambda create-function \
  --function-name $LAMBDA_NAME \
  --runtime nodejs18.x \
  --zip-file fileb://./lambda.zip \
  --handler index.handler \
  # --role "" \
  --region us-east-1