#! /usr/bin/env bash

LAMBDA_NAME=$(cat $(pwd)/scripts/lambda-name | xargs)

aws lambda update-function-code \
  --function-name $LAMBDA_NAME \
  --zip-file fileb://./lambda.zip \
  --region us-east-1